config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  resources :goals
  resources :courses
  resources :orgs
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  
  post 'courses/:id/buy', to: 'courses#buy', as: :buy
  
  get 'users' => 'users#index'
  get 'users/:id' => 'users#show', as: :user

  get 'courses/:id/buy', to: 'courses#buy'
  
  get 'courses/:id/new_evaluation', to: 'courses#new_evaluation'
  
  patch 'courses/:id/evaluate', to: 'courses#evaluate', as: 'evaluation'

  

   

   get 'courses/id' => 'courses#show'
   
   get 'orgs/id' => 'orgs#show'
   
   resources :user_connections, only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
         #,:validatable
         
  has_attached_file :photo, styles: {small: "64x64#", square: "200x200#", large: "600x600#"}
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  has_attached_file :cover, styles: { cover: "800x300#"}

  has_many :user_goals
  has_many :goals, :through => :user_goals
  
  has_many :owned_courses, :class_name => "Course", foreign_key: :owner_id
  
  has_many :user_courses
  has_many :courses, :through => :user_courses
  
  has_many(:user_connections, :foreign_key => :user_a_id, :dependent => :destroy)
  has_many(:reverse_user_connections, :class_name => :UserConnection,
      :foreign_key => :user_b_id, :dependent => :destroy)
  
  has_many :users, :through => :user_connections, :source => :user_b

  
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_action :configure_sign_up_params, only: [:create]
 before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     #devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :photo_file_name, :photo_content_type,:photo_file_size, :photo_updated_at])
     devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation,  :photo, :bio, :username, :name, :goal_ids => []) }  
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     #devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
     devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :photo, :name, :bio, :goal_ids) } 
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show]
   def index
       @users = User.all
   end
   
   
   def recommendCourses
       h = Hash.new{|hsh,key| hsh[key] = {} }
       User.all.each do |user|
           
           user.user_courses.all.each do |user_courses|
               if user_courses != nil
                    if user_courses.graderecommendation >= 0
                        h[user.id].store user_courses.course_id, user_courses.graderecommendation
                    end
                end
            end
    
       end

       
        h2 = Hash.new{|hsh,key| hsh[key] = {} }
       @user = User.find(params[:id])
       @user.user_courses.all.each do |user_courses|
           if user_courses != nil
                    if user_courses.graderecommendation >= 0
                         h2[@user.id].store user_courses.course_id, user_courses.graderecommendation
                    end
                
            end
        end
        
       puts h2
       slope_one = SlopeOne.new
       slope_one.insert(h)
       result = Hash[slope_one.predict(h2[@user.id]).sort_by{|k,v| v}.reverse]
     
       redirect_to '/'
   end
   
   
    private
    # Use callbacks to share common setup or constraints between actions.
        def set_user
          @user = User.find(params[:id])
        end
end

app/views/users/_user.html.erb
   <div class="col-lg-4 col-md-5">
       <div class="card card-user">
           <div class="image">
               <%= image_tag "background.jpg" %>
           </div>
           <div class="content">
               <div class="author">
                   <%= link_to user_path(user) do %>
                       <%= image_tag(user.photo.url(:square), class:"avatar border-white") %>
                   
                   <h4 class="title">
                       <%= user.name %>
                       <br/>
                       <small>@<%= user.email %></small>
                    <% end %>
                   </h4>
               </div>
                <p class="description text-center">
                  <%= user.bio %>
               </p>
           </div>
           <hr>
           <div class="text-center">
              <div class="row">
                   <div class="col-sm-10 col-sm-offset-1">
                   <% if current_user && !(current_user.user_connections.where(user_b_id: user.id).any?) && current_user!=user %>
                       <%= link_to "Criar conexão", user_connections_path(:user_a_id => current_user.id, :user_b_id => user.id), :method => :post, class:"btn btn-success" %>
                   <% elsif current_user && current_user!=user %>
                       <%= link_to "Remover conexão", user_connection_path(current_user.user_connections.where(user_b_id: user.id).first.id), :method => :delete, class:"btn" %>
                   <% end %>
                   </div>
               </div>
               <div class="row">
                    <div class="col-md-3 col-md-offset-1">
                        <h5><%= user.courses.count %><br /><small>Cursos</small></h5>
                    </div>
                    <div class="col-md-4">
                        <h5><%= user.goals.count %><br /><small>Metas</small></h5>
                    </div>
                    <div class="col-md-3">
                        <h5><%= user.user_connections.count %><br /><small>Contatos</small></h5>
                    </div>
               </div>
           </div>

       </div>
   </div>

app/views/users/index.html.erb
<div class="content">
   <div class="container-fluid">
        <div class="row">
       <% if @users.any? %>
            <%= render @users %>
        <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4 col-md-5">
            <div class="card card-user">
                <div class="image">
                    <%= image_tag "background.jpg" %>
                </div>
                <div class="content">
                    <div class="author">
                        <%= image_tag(@user.photo.url(:square) , class:"avatar border-white") %>
                      <h4 class="title"><%= @user.name %><br />
                         <a href="#"><small><%= @user.email %></small></a>
                      </h4>
                    </div>
                    <p class="description text-center">
                        <%= @user.bio %>
                    </p>
                </div>
                <hr>
                <div class="text-center">
                    <div class="row">
                        <div class="col-md-3 col-md-offset-1">
                            <h5><%= @user.courses.count %><br /><small>Cursos</small></h5>
                        </div>
                        <div class="col-md-4">
                            <h5><%= @user.goals.count %><br /><small>Metas</small></h5>
                        </div>
                        <div class="col-md-3">
                            <h5><%= @user.user_connections.count %><br /><small>Contatos</small></h5>
                        </div>
                    </div>
                </div>
            </div>
            <% if @user.user_connections.count!=0 %>
            <div class="card">
                <div class="header">
                    <h4 class="title">Conexões</h4>
                </div>
                <div class="content">
                    <div class="row">
                        <% @user.users.each do |connection| %>
                        <div class="col-xs-3 text-center">
                            <div class="avatar">
                                <%= link_to user_path(connection) do %>
                                    <%= image_tag(connection.photo.url(:small), class:"img-circle img-no-padding img-responsive") %>
                                <% end %>
                            </div>
                        </div>
                        <% end %>
                    </div>
                </div>
            </div>
            <% end %>
            <% if @user.goals.count!=0 %>
            <div class="card">
                <div class="header">
                    <h4 class="title">Metas</h4>
                </div>
                <div class="content">
                    <div class="row">
                        <% @user.goals.each do |goal| %>
                        <div class="col-xs-12">
                            <div>
                               <%= link_to goal_path(goal) do %>
                                    <h4><%= goal.name %></h4>    
                               <% end %>
                            </div>
                        </div>
                        <% end %>
                    </div>
                </div>
            </div>
            <% end %>
        </div>
        <div class="col-lg-8 col-md-7">
            <% @user.courses.each do |course| %>
            <div class="card card-user">
                <div class="row" style="min-height: 200px;">
                    <div class="col-md-3">
                        <div class="panel-card">
                            <%= link_to course_path(course) do %>
                                <%= image_tag(course.picture.url(:square) , class:"avatar border-white") %>
                                <h4 class="title"><%= course.name %><br /></h4>
                            <% end %>
                              
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="content">
                            <h3><%= link_to course.org.name, org_path(course.org) %></h3>
                            <p><small><%= course.intro %></small></p>
                        </div>
                            
                    </div>
                    <div class="col-md-3">
                        <div class="content">
                            <div class="row">
                               <div class="icon-big icon-warning text-center vertically-align-icon col-xs-4 col-xs-offset-2">
                                    <i class="fa fa-star"></i>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <h3><%= course.grade %></h3>
                                </div>
                            </div>
                            <div class="row">
                                <div class="icon-big text-center vertically-align-icon col-xs-4 col-xs-offset-2
                                <% if course.grade!=nil %> icon-default" style="color: silver;" <%else%>icon-success"<%end%> >
                                    <i class="fa fa-check-circle-o"></i>
                                </div>
                                <div class="col-xs-4">
                                    <h3></h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
        </div>


    </div>
</div>