config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  resources :goals
  resources :courses
  resources :orgs
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  
  post 'courses/:id/buy', to: 'courses#buy', as: :buy
  
  get 'users' => 'users#index'
  get 'users/:id' => 'users#show', as: :user

  get 'courses/:id/buy', to: 'courses#buy'
  
  get 'courses/:id/new_evaluation', to: 'courses#new_evaluation'
  
  patch 'courses/:id/evaluate', to: 'courses#evaluate', as: 'evaluation'

  

   

   get 'courses/id' => 'courses#show'
   
   get 'orgs/id' => 'orgs#show'
   
   resources :user_connections, only: [:create, :destroy]

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end
  
  def buy
    course = Course.find(params[:id])
    @user = current_user
    if !@user.courses.exists?(params[:id])
      @user.courses << course
    end
    @user.save!
    redirect_to '/'
  end
  

  # GET /courses/new
  def new
    @course = Course.new
    
  end

  # GET /courses/1/edit
  def edit
  end
  
  

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.owner_id = current_user.id
    
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def new_evaluation
    @course = Course.find(params[:id])
  end
  
  
  def evaluate
    @course = Course.find (params[:id])
    @course.evaluationNumber = @course.evaluationNumber + 1
    difficulty = (@course.difficulty*(@course.evaluationNumber-1) + evaluate_params[:difficulty].to_f)/(@course.evaluationNumber)
    @course.difficulty = difficulty
    if difficulty < 1.67
      
      @course.level = "Fácil"
    elsif difficulty > 1.67 && difficulty < 3.33
      @course.level = "Intermediário"
    
    else
      @course.level = "Avançado"
    
    end
    @course.save!
    redirect_to '/'
  end
  
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :intro, :org_id, :description, :content, :difficulty, :capacity, :participants)
    end
    
    def evaluate_params
      params.require(:course).permit(:difficulty)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
            <div class="col-lg-4 col-md-5">
                <div class="card card-user">
                    <div class="image">
                        <%= image_tag course.cover %>
                    </div>
                    <div class="content">
                        <div class="author">
                          <%= image_tag(course.picture, class:"avatar border-white") %>
                          <h4 class="title"><%= course.name %><br />
                          <% if course.org %>
                             <small><%= course.org.name %></small>
                         <% end %>
                          </h4>
                        </div>
                        <p class="description text-center">
                           <%= course.intro %>
                        </p>
                    </div>
                    <hr>
                    <div class="text-center">
                        <div class="row">
                            <div class="col-md-3 col-md-offset-1">
                                 <h5><%= course.capacity %><br /><small>Vagas</small></h5>
                            </div>
                             <div class="col-md-4">
                               <h5><% course.start %><br /><small>Início</small></h5>
                            </div>
                            <div class="col-md-3">
                               <h5><% course.end %><br /><small>Término</small></h5>
                            </div>
                        </div>
                        <hr>
                         <div class="row">
                            <div class="col-md-4 col-md-offset-1">
                                 <h5>R$ <% course.price %><br /><small>Preço</small></h5>
                            </div>
                            <div class="col-md-5">
                                <%= link_to "Saiba mais", course_path(course), class:"btn btn-info btn-fill btn-wd vertically-align-icon"%>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

app/views/courses/_form.html.erb
    <div class="content">
        <%= form_for(@course) do |f| %>
        
          <div class="row">
                <%= devise_error_messages! %>
                <div class="col-md-12">
                    <div class="form-group">
                      <%= f.label :"Nome do curso" %><br />
                      <%= f.text_field :name, autofocus: true, class:"form-control border-input" %>
                    
                    </div>
                </div>
            </div>
        
             <div class="row">
                <%= devise_error_messages! %>
                <div class="col-md-12">
                    <div class="form-group">
                       <%= f.label :"Introdução" %><br>
                         <%= f.text_field :intro, autofocus: true, class:"form-control border-input" %>
                    </div>
                </div>
            </div>
            
                <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                         <%= f.label :"Descrição" %><br>
                         <%= f.text_field :description,  autofocus: true, class:"form-control border-input" %>
                    </div>
                </div>
            </div>
                   
             <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                         <%= f.label :"Conteúdo" %><br>
                         <%= f.text_field :content,  autofocus: true, class:"form-control border-input" %>
                    </div>
                </div>
            </div>
             
            <div class="row">
              <div class="col-md-4">
                <div class="form-group">
                  <%= f.label :"Nível" %><br />
                  <%= f.text_field :difficulty, autocomplete: "off", class:"form-control border-input"  %>
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <%= f.label :Vagas %><br />
                  <%= f.text_field :capacity, autocomplete: "off", class:"form-control border-input" %>
                </div> 
              </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <%= f.label :"Participantes" %> <br />
                    <%= f.text_field :participants, autocomplete: "off" , class:"form-control border-input" %>
                  </div>
                </div>
            </div>
            
               <div class="row">
              <div class="col-md-4">
                <div class="form-group">
                  <%= f.label :"Data de início" %><br />
                  <%= f.text_field :start, autocomplete: "off", class:"form-control border-input"  %>
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <%= f.label :"Data de término" %><br />
                  <%= f.text_field :end, autocomplete: "off", class:"form-control border-input" %>
                </div> 
              </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <%= f.label :"Preço" %> <br />
                    <%= f.text_field :price, autocomplete: "off" , class:"form-control border-input" %>
                  </div>
                </div>
            </div>
            <div class="row">
              <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
                <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
              <% end %>
            </div>

            <div class="text-center">
                <%= f.submit "Criar" , class:"btn btn-info btn-fill btn-wd" %>
            </div>
            <div class="clearfix"></div>
        <% end %>
    </div>
</div>

  <div class="field">
    <%= f.label :intro %><br>
    <%= f.text_field :intro %>
  </div>
  <div class="field">
    <%= f.label :faculdade %>
    <%= f.collection_select :org_id, Org.all, :id, :name, {include_blank: false}, {multiple: false, class:"form-control"} %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :participants %><br>
    <%= f.number_field :participants %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4 col-md-5">
            <div class="card card-user">
                <div class="image">
                    <%= image_tag @course.cover %>
                </div>
                <div class="content">
                    <div class="author">
                        <%= image_tag(@course.org.picture , class:"avatar border-white") %>
                      <h4 class="title"><%= @course.name %><br />
                         <a href="#"><small><%= @course.org.name %></small></a>
                      </h4>
                    </div>
                    <p class="description text-center">
                        <%= @course.intro %>
                    </p>
                </div>
                <hr>
                <div class="text-center">
                    <div class="row">
                        <div class="col-md-3 col-md-offset-1">
                            <h5><%= @course.capacity %><br /><small>Vagas</small></h5>
                        </div>
                        <div class="col-md-4">
                            <h5><%= @course.start%><br /><small>Início</small></h5>
                        </div>
                        <div class="col-md-3">
                            <h5><%= @course.end %><br /><small>Término</small></h5>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                       <h5><%= @course.price %><br /><small>Preço</small></h5>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="header">
                    <h4 class="title">Cancelar conta</h4>
                </div>
                <div class="content">
                    <%= button_to "Remover conta", registration_path(resource_name), data: { confirm: "Tem certeza?" }, method: :delete, class:"btn btn-danger" %>
                </div>
            </div>
        </div>
        <div class="col-lg-8 col-md-7">
            <div class="card">
                <div class="header">
                    <h4 class="title">Editar Curso</h4>
                </div>
                <%= render 'form' %>
            </div>
        </div>
    </div>
</div>



<%= link_to 'Voltar', courses_path, class:"btn btn-sm btn-success btn-icon center" %>

app/views/courses/index.html.erb
<<<<<<< HEAD
<div class="content">
 
    <div class="container-fluid">
        <div class="row">
<% if @courses.any? %>
    <%= render @courses %>
<% end %>
 </div>
 <%= link_to 'Novo Curso', new_course_path, class:"btn btn-success" %>
  </div>
 </div>
<br>

app/views/courses/new.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="card">
                <div class="header">
                    <h4 class="title centralize">Criar novo curso</h4>
                </div>
                    <%= render 'form' %>
                </div>
    </div>
</div>

<%= link_to 'Back', courses_path %>

app/views/courses/new_evaluation.html.erb
<%= form_for @course, url: 'evaluate', :html => { :multipart => true } do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this evaluation from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :Nota %><br>
    <%= f.number_field :difficulty, min:0, max:5  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/show.html.erb
<!--Método dos cursos-->

<div class="container-fluid">
<div class="row">
    <div class="col-lg-4 col-md-5">
        <div class="card card-user">
            <div class="image">
                <%= image_tag @course.cover %>
            </div>
            <div class="content">
                <div class="author">
                  <%= image_tag(@course.picture, class:"avatar border-white") %>
                  <h4 class="title"><%= @course.name %><br />
                     <small><%= link_to @course.org.name, org_path(@course.org) %></small>
                  </h4>
                </div>
                <p class="description text-center">
                    <%= @course.intro %>
                </p>
            </div>
            <hr>
            <div class="text-center">
                <div class="row">
                    <div class="col-md-3 col-md-offset-1">
                        <h5><%= @course.capacity %><br /><small>Vagas</small></h5>
                    </div>
                    <div class="col-md-4">
                       <h5><%= @course.start %><br /><small>Início</small></h5>
                    </div>
                    <div class="col-md-3">
                      <h5><%= @course.end %><br /><small>Término</small></h5>
                    </div>
                </div>
                <hr>
                 <div class="row">
                    <h5>R$ <%= @course.price %><br /><small>Preço</small></h5>
                </div>
            </div>
        </div>
        
        
    <%if @course.users.any? %>

        <div class="card">
            <div class="header" style="text-align:center">
                <h4 class="title">Inscritos</h4>
            </div>
            <div class="content">
                <ul class="list-unstyled team-members">
                    <% @course.users.each do |user| %> 
                            <li>
                                <div class="row">
                                    <div class="col-xs-3">
                                        <div class="avatar">
                                            <img src=<%= user.photo%> alt="Circle Image" class="img-circle img-no-padding img-responsive">
                                        </div>
                                    </div>
                                    <div class="col-xs-6">
                                        <%= user.name%>
                                    </div>
                                    <div class="col-xs-3 text-right">
                                        <btn class="btn btn-sm btn-success btn-icon"><i class="fa fa-mail-forward"></i></btn>
                                    </div>
                                </div>
                            </li>
                        <%end%>
                </ul>
            </div>
        </div>
    <%end%>
    
    </div>
    <div class="col-lg-8 col-md-7">
        <div class="card">
            <div class="header">
                <div class ="col-lg-8">
                    <h2 class="title" class="text-center"><%= @course.name %></h2>
                </div>
                <div class ="col-lg-4">
                    <%= link_to "Inscrever-se", buy_path , class:"btn btn-info btn-fill btn-wd"%>
                </div>
            </div>
            <div class="row"></div>
            <div class="content">
                <h3>Descrição</h3>
                <p><%= @course.description %></p>
                 <hr>
                <h3>Ementa</h3>
                <p><%= @course.content %></p>
            </div>
        </div>
   
         <%if @course.owner %>
         
             <div class="card card-user">
                <div class="header">
                    <h3>Responsáveis</h3>
                </div>
                <div class="content">
                        <div class="row">
                            <div  class=" content col-md-3 col-md-offset-1">
                                     <%= image_tag(@course.owner.photo, class:"avatar border-white") %>
                                      <h4 class="title"><%@course.owner.name%></h4>
                            </div>
                            <div class="col-md-7 card-user description">
                                <p class="vertically-align">
                                        <%= @course.owner.bio %>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
        <%end%>   
        
            <div class="row">
                <div class="col-lg-4 col-sm-6">
                    <div class="card">
                        <div class="content">
                            <div class="row">
                                <div class="col-xs-5">
                                    <div class="icon-big icon-warning text-center vertically-align-icon">
                                        <i class="fa fa-star"></i>
                                    </div>
                                </div>
                                <div class="col-xs-7">
                                    <div class="numbers">
                                        <p>Nota</p><br />
                                        <%= @course.grade %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="card">
                        <div class="content">
                            <div class="row">
                                <div class="col-xs-5">
                                    <div class="icon-big icon-success text-center vertically-align-icon">
                                        <i class="fa fa-book"></i>
                                    </div>
                                </div>
                                <div class="col-xs-7">
                                    <div class="numbers">
                                        <p>Nível</p><br />
                                        <%= @course.difficulty %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="card">
                        <div class="content">
                            <div class="row">
                                <div class="col-xs-5">
                                    <div class="icon-big icon-danger text-center vertically-align-icon">
                                        <i class="fa fa-group"></i>
                                    </div>
                                </div>
                                <div class="col-xs-7">
                                    <div class="numbers">
                                        <p>Já cursaram</p><br />
                                            <%= @course.participants %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row"></div>
            <div class="row">
                <%if current_user == @course.owner %>
                <%= link_to 'Editar Curso', edit_course_path(@course), class:"btn btn-info btn-fill btn-wd", style:"margin:auto"%> 
                <%end%>
            </div>
            
        </div>
    </div>
    
</div>