config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  resources :goals
  resources :courses
  resources :orgs
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  
  post 'courses/:id/buy', to: 'courses#buy', as: :buy
  
  get 'users' => 'users#index'
  get 'users/:id' => 'users#show', as: :user

  get 'courses/:id/buy', to: 'courses#buy'
  
  get 'courses/:id/new_evaluation', to: 'courses#new_evaluation'
  
  patch 'courses/:id/evaluate', to: 'courses#evaluate', as: 'evaluation'

  

   

   get 'courses/id' => 'courses#show'
   
   get 'orgs/id' => 'orgs#show'
   
   resources :user_connections, only: [:create, :destroy]

end

app/models/goal.rb
class Goal < ActiveRecord::Base
    has_many :courses
    
    has_many :user_goals
    has_many :users, :through => :user_goals
    
    has_many :course_goals
    has_many :courses, :through => :course_goals
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:name)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goals/_goal.html.erb
<div class="col-lg-4 col-md-5">
    <div class="card card-user">
        <div class="image">
            <%= image_tag "background.jpg" %>
        </div>
        <div class="content">
            <div class="author">
                <%= image_tag "tim_80x80.png", class:"avatar border-white" %>
                <h4 class="title"><%= goal.name %><br/>
                    <small><%= goal.courses.count %> Cursos</small>
                </h4>
            </div>
            <div class="row text-center">
                <%= link_to "Seguir camminho", "#", class: "btn btn-success" %> 
            </div>
        </div>
        <hr>
        <div class="text-center">

            <% goal.courses.each do |curso| %>
            <div class="row">
                <h3><%= link_to curso.name, course_path(curso) %></h3>
            </div>
            <% end %>

        </div>
    </div>
</div>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <% if @goals.any? %>
                <%= render @goals %>
            <% end %>
        </div> 
        <%= link_to 'Novo caminho', new_goal_path, class:"btn btn-success" %>
    </div> 
</div> 

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @goal.name %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>