config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  resources :goals
  resources :courses
  resources :orgs
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  
  post 'courses/:id/buy', to: 'courses#buy', as: :buy
  
  get 'users' => 'users#index'
  get 'users/:id' => 'users#show', as: :user

  get 'courses/:id/buy', to: 'courses#buy'
  
  get 'courses/:id/new_evaluation', to: 'courses#new_evaluation'
  
  patch 'courses/:id/evaluate', to: 'courses#evaluate', as: 'evaluation'

  

   

   get 'courses/id' => 'courses#show'
   
   get 'orgs/id' => 'orgs#show'
   
   resources :user_connections, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>

                <li>
                    <a href="http://www.fb.com/escolapirata">
                        Facebook
                    </a>
                </li>
                <li>
                    <a href="http://www.medium.com/escola-pirata">
                       Blog
                    </a>
                </li>
            </ul>
        </nav>
		<div class="copyright pull-right">
            &copy; 2016, made with <i class="fa fa-heart heart"></i> by <a href="http://www.escolapirata.com">Escola Pirata</a>
        </div>
    </div>
</footer>

app/views/layouts/_modals.html.erb
  <!-- Modal -->
  <div class="modal fade" id="sign-in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Entrar</h4>
        </div>
        <div class="modal-body">
          <div class="content">
            <div class="form-group col-xs-12">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true, class: "form-control border-input col-xs-12" %>
            </div>
          
            <div class="form-group col-xs-12">
              <%= f.label :password %><br />
              <%= f.password_field :password, autocomplete: "off", class: "form-control border-input col-xs-12"  %>
            </div>
          
  
          </div>
          <div class="row form-group">
            <div class="col-sm-5 col-sm-offset-1">
              <% if devise_mapping.rememberable? -%>
                <div class="form-group checkbox">
                  <%= f.check_box :remember_me %>
                  <%= f.label "Lembrar de mim" %>
                </div>
              <% end -%>
            </div>
            <div class="col-sm-3">
               <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
            <div class="col-sm-3">
              <%= f.submit "Entrar", class:"btn btn-fill" %>             
            </div>
          </div>
  
         
        </div>
        <% end %>
        <div class="modal-footer">
            <%= render "devise/shared/links" %>
        </div>
      </div>
    </div>
  </div>
  
  
  <!-- Modal -->
  <div class="modal fade" id="sign-up" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Cadastrar</h4>
        </div>
        <div class="modal-body">
          <div class="content">
           <%= devise_error_messages! %>
            <div class="form-group col-xs-12">
              <%= f.label("E-mail") %><br />
              <%= f.email_field :email, autofocus: true, class: "form-control border-input col-xs-12" %>
            </div>
            <div class="form-group col-xs-12">
              <%= f.label("Senha") %>
              <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "off", class: "form-control border-input col-xs-12"   %>
            </div>
            
            <div class="form-group col-xs-12">
              <%= f.label("Confirme sua senha") %><br />
              <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control border-input col-xs-12"  %>
            </div>
            
            <div class="form-group col-xs-12">
              <%= f.label("Foto") %>
              <%= f.file_field :photo, class: "form-control border-input col-xs-12"   %>
            </div>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          <%= f.submit "Cadastrar", class:"btn btn-fill pull-right" %>
         
        </div>
        <% end %>
        <div class="modal-footer">
            <%= render "devise/shared/links" %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar bar1"></span>
                <span class="icon-bar bar2"></span>
                <span class="icon-bar bar3"></span>
            </button>
            <a class="navbar-brand" href="#">Livres para aprender!</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-user"></i>
						<p>Logado como: <strong><%= current_user.email %></strong></p>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Editar perfil", edit_user_registration_path %></li>
                        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                      </ul>
                </li>
                <% else %>
                    <%= link_to "Cadastrar", new_user_registration_path, class:"btn btn-primary btn-lg" %>
                    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#sign-in">
                      Entrar
                    </button>
                <% end %>
                

            </ul>

        </div>
    </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="sidebar" data-background-color="black" data-active-color="danger">

<!--
	Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
	Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
-->

	<div class="sidebar-wrapper">
        <div class="logo">
            <h1 align="center">
                <%= link_to root_path do %>
                <%= image_tag "ahoy.png", :style => "width: 100%;" %>
                <%end%>
            </h1>
            

        </div>

        <ul class="nav">
            <li class="<%= 'active' if controller.controller_name=="goals" %>">
                <%= link_to(goals_path) do %>
                    <i class="fa fa-map-o"></i>
                    <p>Caminhos</p>
                <% end %>
            </li>
            <li class="<%= 'active' if controller.controller_name=="courses" %>">
                <%= link_to(courses_path) do %>
                    <i class="fa fa-book"></i>
                    <p>Cursos</p>
                <% end %>
            </li>
            <li class="<%= 'active' if controller.controller_name=="orgs" %>">
                <%= link_to(orgs_path) do %>
                    <i class="fa fa-university"></i>
                    <p>Faculdades</p>
                <% end %>
            </li>
            <li class="<%= 'active' if controller.controller_name=="users" %>">
                <%= link_to(users_path)  do %>
                    <i class="fa fa-users"></i>
                    <p>Usuários</p>
                <% end %>
            </li>

        </ul>    

        
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ahooy!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:400,300" rel="stylesheet" type="text/css">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
  

<div class="wrapper">
  <%= render 'layouts/sidebar' %>
  <div class="main-panel">
    <%= render 'layouts/navbar' %>

    <div class="content">
      <div>
        <% if notice %>
          <div class="alert alert-info" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <span><%= notice %></span>
          </div>
        <% end %>
        <% if alert %>  
          <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <span><%= alert %></span>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </div>
</div>

<%= render 'layouts/modals' %>

</body>
</html>